# Make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable deep sleep
CONFIG_ZMK_SLEEP=y

# Enable bluetooth and battery reporting to host
## *DISABLED*
CONFIG_BT=n
CONFIG_ZMK_BLE=n

# Bluetooth connection counts
#CONFIG_BT_MAX_CONN=2
#CONFIG_BT_MAX_PAIRED=2